import { IOption } from './IOption';

export const opciones: IOption[] = [
    {
        image: 'assets/img/cotizacion.png',
        route: '/buscar-cotizacion',
        image_width: '50px',
        image_heigth: '50px',
        tooltip: 'Cotización',
        color: 'color1',
    },
    {
        image: 'assets/img/ventas.png',
        route: '/buscar-venta',
        image_width: '50px',
        image_heigth: '50px',
        tooltip: 'Ventas',
        color: 'color2',
    },
    {
        image: 'assets/img/facturas.png',
        route: '/buscar-cotizacion',
        image_width: '50px',
        image_heigth: '50px',
        tooltip: 'Facturas',
        color: 'color3',
    },
    {
        image: 'assets/img/producto.png',
        route: '/buscar-producto',
        image_width: '50px',
        image_heigth: '50px',
        tooltip: 'Productos',
        color: 'color4',
    },
    {
        image: 'assets/img/proveedores.png',
        route: '/buscar-proveedor',
        image_width: '50px',
        image_heigth: '50px',
        tooltip: 'Proveedores',
        color: 'color5',
    },
    {
        image: 'assets/img/almacen.png',
        route: '/almacen',
        image_width: '50px',
        image_heigth: '50px',
        tooltip: 'Almacén',
        color: 'color6',
    },
    {
        image: 'assets/img/usuarios.png',
        route: '/buscar-usuario',
        image_width: '50px',
        image_heigth: '50px',
        tooltip: 'Usuarios',
        color: 'color7',
    },
    {
        image: 'assets/img/clientes.png',
        route: '/buscar-cliente',
        image_width: '50px',
        image_heigth: '50px',
        tooltip: 'Clientes',
        color: 'color8',
    },
    {
        image: 'assets/img/reportes.png',
        route: '/buscar-cotizacion',
        image_width: '50px',
        image_heigth: '50px',
        tooltip: 'Reportes',
        color: 'color9',
    }
]
